#      __  ____                 _   __                
#    /  |/  (_)_____________  / | / /___ _   ______ _
#   / /|_/ / / ___/ ___/ __ \/  |/ / __ \ | / / __ `/
#  / /  / / / /__/ /  / /_/ / /|  / /_/ / |/ / /_/ / 
# /_/  /_/_/\___/_/   \____/_/ |_/\____/|___/\__,_/  
#                                                  
# Mercury 2 User Constraints File
# Revision 0.B
# Copyright (c) 2019 MicroNova, LLC
# www.micro-nova.com

# general settings
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

# on-board system oscillator
set_property PACKAGE_PIN N14 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN H16 [get_ports {clk_en}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_en}]

# on-board user LEDs
set_property PACKAGE_PIN M1 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN A14 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN A13 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]

# FPGA: control signals
set_property PACKAGE_PIN H10 [get_ports {fpga_done}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_done}]
set_property PACKAGE_PIN L9 [get_ports {fpga_prog}]
set_property IOSTANDARD LVCMOS33 [get_ports {fpga_prog}]


# FPGA Direct I/O
set_property PACKAGE_PIN C12 [get_ports {dio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[0]}]
set_property PACKAGE_PIN C11 [get_ports {dio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[1]}]
set_property PACKAGE_PIN D9 [get_ports {dio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[2]}]
set_property PACKAGE_PIN A9 [get_ports {dio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[3]}]
set_property PACKAGE_PIN A8 [get_ports {dio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[4]}]
set_property PACKAGE_PIN A10 [get_ports {dio[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[5]}]
set_property PACKAGE_PIN B9 [get_ports {dio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[6]}]
set_property PACKAGE_PIN B6 [get_ports {dio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[7]}]
set_property PACKAGE_PIN B5 [get_ports {dio[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[8]}]
set_property PACKAGE_PIN E12 [get_ports {dio[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dio[9]}]

# 5V tolerant level shifted I/O
set_property PACKAGE_PIN G1 [get_ports {io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[0]}]
set_property PACKAGE_PIN G2 [get_ports {io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[1]}]
set_property PACKAGE_PIN F2 [get_ports {io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[2]}]
set_property PACKAGE_PIN E1 [get_ports {io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[3]}]
set_property PACKAGE_PIN E2 [get_ports {io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[4]}]
set_property PACKAGE_PIN C2 [get_ports {io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[5]}]
set_property PACKAGE_PIN B2 [get_ports {io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[6]}]
set_property PACKAGE_PIN B1 [get_ports {io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[7]}]
set_property PACKAGE_PIN A2 [get_ports {io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[8]}]
set_property PACKAGE_PIN H2 [get_ports {io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[9]}]
set_property PACKAGE_PIN B10 [get_ports {io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[10]}]
set_property PACKAGE_PIN C8 [get_ports {io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[11]}]
set_property PACKAGE_PIN C9 [get_ports {io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[12]}]
set_property PACKAGE_PIN T13 [get_ports {io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[13]}]
set_property PACKAGE_PIN R12 [get_ports {io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[14]}]
set_property PACKAGE_PIN P11 [get_ports {io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[15]}]
set_property PACKAGE_PIN T2 [get_ports {io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[16]}]
set_property PACKAGE_PIN T4 [get_ports {io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[17]}]
set_property PACKAGE_PIN T5 [get_ports {io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[18]}]
set_property PACKAGE_PIN T7 [get_ports {io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[19]}]
set_property PACKAGE_PIN K5 [get_ports {io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[20]}]
set_property PACKAGE_PIN A3 [get_ports {io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[21]}]
set_property PACKAGE_PIN C6 [get_ports {io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[22]}]
set_property PACKAGE_PIN D4 [get_ports {io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[23]}]
set_property PACKAGE_PIN F5 [get_ports {io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[24]}]
set_property PACKAGE_PIN D8 [get_ports {io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[25]}]
set_property PACKAGE_PIN P1 [get_ports {io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[26]}]
set_property PACKAGE_PIN C7 [get_ports {io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[27]}]
set_property PACKAGE_PIN M2 [get_ports {io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[28]}]
set_property PACKAGE_PIN N1 [get_ports {io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[29]}]
set_property PACKAGE_PIN C1 [get_ports {io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[30]}]
set_property PACKAGE_PIN D1 [get_ports {io[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[31]}]
set_property PACKAGE_PIN L2 [get_ports {io[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[32]}]
set_property PACKAGE_PIN G5 [get_ports {io[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[33]}]
set_property PACKAGE_PIN H5 [get_ports {io[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[34]}]
set_property PACKAGE_PIN H1 [get_ports {io[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[35]}]
set_property PACKAGE_PIN K1 [get_ports {io[36]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[36]}]
set_property PACKAGE_PIN K2 [get_ports {io[37]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[37]}]
set_property PACKAGE_PIN J1 [get_ports {io[38]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[38]}]
set_property PACKAGE_PIN J3 [get_ports {io[39]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io[39]}]

# DAC interface
set_property PACKAGE_PIN K12 [get_ports {dac_sdi}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sdi}]
set_property PACKAGE_PIN P14 [get_ports {dac_ldac}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ldac}]
set_property PACKAGE_PIN N13 [get_ports {dac_sck}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck}]
set_property PACKAGE_PIN K16 [get_ports {dac_csn}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_csn}]

# ADC interface
set_property PACKAGE_PIN G15 [get_ports {adc_miso}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_miso}]
set_property PACKAGE_PIN J16 [get_ports {adc_mosi}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_mosi}]
set_property PACKAGE_PIN P10 [get_ports {adc_sck}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_sck}]
set_property PACKAGE_PIN K15 [get_ports {adc_csn}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_csn}]

# XADC differential input
set_property PACKAGE_PIN H8 [get_ports {xadc_vp}]
set_property IOSTANDARD LVCMOS33 [get_ports {xadc_vp}]
set_property PACKAGE_PIN J7 [get_ports {xadc_vn}]
set_property IOSTANDARD LVCMOS33 [get_ports {xadc_vn}]
set_property PACKAGE_PIN J8 [get_ports {xadc_vref_p}]
set_property IOSTANDARD LVCMOS33 [get_ports {xadc_vref_p}]
set_property PACKAGE_PIN H7 [get_ports {xadc_vref_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {xadc_vref_n}]


# SRAM: address bus
set_property PACKAGE_PIN M4 [get_ports {sram_a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[0]}]
set_property PACKAGE_PIN N3 [get_ports {sram_a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[1]}]
set_property PACKAGE_PIN N4 [get_ports {sram_a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[2]}]
set_property PACKAGE_PIN P3 [get_ports {sram_a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[3]}]
set_property PACKAGE_PIN M5 [get_ports {sram_a[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[4]}]
set_property PACKAGE_PIN E5 [get_ports {sram_a[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[5]}]
set_property PACKAGE_PIN D5 [get_ports {sram_a[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[6]}]
set_property PACKAGE_PIN D3 [get_ports {sram_a[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[7]}]
set_property PACKAGE_PIN B7 [get_ports {sram_a[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[8]}]
set_property PACKAGE_PIN B4 [get_ports {sram_a[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[9]}]
set_property PACKAGE_PIN J4 [get_ports {sram_a[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[10]}]
set_property PACKAGE_PIN H4 [get_ports {sram_a[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[11]}]
set_property PACKAGE_PIN H3 [get_ports {sram_a[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[12]}]
set_property PACKAGE_PIN G4 [get_ports {sram_a[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[13]}]
set_property PACKAGE_PIN E6 [get_ports {sram_a[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[14]}]
set_property PACKAGE_PIN A7 [get_ports {sram_a[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[15]}]
set_property PACKAGE_PIN A5 [get_ports {sram_a[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[16]}]
set_property PACKAGE_PIN A4 [get_ports {sram_a[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[17]}]
set_property PACKAGE_PIN C4 [get_ports {sram_a[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[18]}]
set_property PACKAGE_PIN J5 [get_ports {sram_a[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[19]}]
set_property PACKAGE_PIN C3 [get_ports {sram_a[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_a[20]}]

# SRAM: data bus
set_property PACKAGE_PIN L5 [get_ports {sram_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_d[0]}]
set_property PACKAGE_PIN L3 [get_ports {sram_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_d[1]}]
set_property PACKAGE_PIN L4 [get_ports {sram_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_d[2]}]
set_property PACKAGE_PIN R2 [get_ports {sram_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_d[3]}]
set_property PACKAGE_PIN F3 [get_ports {sram_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_d[4]}]
set_property PACKAGE_PIN F4 [get_ports {sram_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_d[5]}]
set_property PACKAGE_PIN E3 [get_ports {sram_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_d[6]}]
set_property PACKAGE_PIN D6 [get_ports {sram_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_d[7]}]

# SRAM: control signals
set_property PACKAGE_PIN R1 [get_ports {sram_wen}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_wen}]
set_property PACKAGE_PIN M6 [get_ports {sram_cen}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_cen}]

# Ethernet PHY interface
set_property PACKAGE_PIN C14 [get_ports {eth_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd[0]}]
set_property PACKAGE_PIN B14 [get_ports {eth_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd[1]}]
set_property PACKAGE_PIN B16 [get_ports {eth_txen}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txen}]
set_property PACKAGE_PIN E13 [get_ports {eth_crsdv}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_crsdv}]
set_property PACKAGE_PIN H12 [get_ports {eth_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd[0]}]
set_property PACKAGE_PIN H13 [get_ports {eth_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd[1]}]
set_property PACKAGE_PIN L13 [get_ports {eth_rxer}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxer}]
set_property PACKAGE_PIN D14 [get_ports {eth_mdc}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_mdc}]
set_property PACKAGE_PIN D16 [get_ports {eth_mdio}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_mdio}]
set_property PACKAGE_PIN G11 [get_ports {eth_intn}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_intn}]
set_property PACKAGE_PIN F15 [get_ports {eth_rstn}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rstn}]
set_property PACKAGE_PIN A12 [get_ports {eth_led1}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_led1}]
set_property PACKAGE_PIN A15 [get_ports {eth_led2}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_led2}]
set_property PACKAGE_PIN D13 [get_ports {eth_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_clk}]

# FTDI: serial communication interface
set_property PACKAGE_PIN E15 [get_ports {ftdi_acbus[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_acbus[3]}]
set_property PACKAGE_PIN D15 [get_ports {ftdi_acbus[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_acbus[4]}]
set_property PACKAGE_PIN E16 [get_ports {ftdi_acbus[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_acbus[5]}]
set_property PACKAGE_PIN G14 [get_ports {ftdi_acbus[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_acbus[6]}]
set_property PACKAGE_PIN G16 [get_ports {ftdi_acbus[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_acbus[7]}]
set_property PACKAGE_PIN P16 [get_ports {ftdi_bcbus[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bcbus[0]}]
set_property PACKAGE_PIN T15 [get_ports {ftdi_bcbus[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bcbus[1]}]
set_property PACKAGE_PIN R16 [get_ports {ftdi_bcbus[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bcbus[2]}]
set_property PACKAGE_PIN T14 [get_ports {ftdi_bcbus[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bcbus[3]}]
set_property PACKAGE_PIN R15 [get_ports {ftdi_bcbus[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bcbus[4]}]
set_property PACKAGE_PIN P15 [get_ports {ftdi_bcbus[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bcbus[5]}]
set_property PACKAGE_PIN T12 [get_ports {ftdi_bcbus[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bcbus[6]}]
set_property PACKAGE_PIN E11 [get_ports {ftdi_bdbus[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bdbus[0]}]
set_property PACKAGE_PIN N11 [get_ports {ftdi_bdbus[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bdbus[1]}]
set_property PACKAGE_PIN L14 [get_ports {ftdi_bdbus[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bdbus[2]}]
set_property PACKAGE_PIN M14 [get_ports {ftdi_bdbus[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bdbus[3]}]
set_property PACKAGE_PIN T9 [get_ports {ftdi_bdbus[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bdbus[4]}]
set_property PACKAGE_PIN M16 [get_ports {ftdi_bdbus[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bdbus[5]}]
set_property PACKAGE_PIN M15 [get_ports {ftdi_bdbus[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bdbus[6]}]
set_property PACKAGE_PIN N16 [get_ports {ftdi_bdbus[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_bdbus[7]}]
set_property PACKAGE_PIN T8 [get_ports {ftdi_pwren}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_pwren}]
set_property PACKAGE_PIN H14 [get_ports {ftdi_suspend}]
set_property IOSTANDARD LVCMOS33 [get_ports {ftdi_suspend}]

# Flash: interface
set_property PACKAGE_PIN J13 [get_ports {flash_mosi}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_mosi}]
set_property PACKAGE_PIN J14 [get_ports {flash_miso}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_miso}]
set_property PACKAGE_PIN L12 [get_ports {flash_csn}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_csn}]
set_property PACKAGE_PIN E8 [get_ports {flash_sck}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_sck}]

# JTAG: interface
set_property PACKAGE_PIN N7 [get_ports {jtag_tdi}]
set_property IOSTANDARD LVCMOS33 [get_ports {jtag_tdi}]
set_property PACKAGE_PIN N8 [get_ports {jtag_tdo}]
set_property IOSTANDARD LVCMOS33 [get_ports {jtag_tdo}]
set_property PACKAGE_PIN L7 [get_ports {jtag_tck}]
set_property IOSTANDARD LVCMOS33 [get_ports {jtag_tck}]
set_property PACKAGE_PIN M7 [get_ports {jtag_tms}]
set_property IOSTANDARD LVCMOS33 [get_ports {jtag_tms}]

# wifi
set_property PACKAGE_PIN R6 [get_ports {wifi_rx}]
set_property IOSTANDARD LVCMOS33 [get_ports {wifi_rx}]
set_property PACKAGE_PIN R7 [get_ports {wifi_tx}]
set_property IOSTANDARD LVCMOS33 [get_ports {wifi_tx}]
set_property PACKAGE_PIN R5 [get_ports {wifi_rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {wifi_rst}]
set_property PACKAGE_PIN R8 [get_ports {wifi_en}]
set_property IOSTANDARD LVCMOS33 [get_ports {wifi_en}]

